src/Entity/User.php
<?php


namespace App\Entity;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $phone;

    /**
     * @ORM\Column(type="integer")
     */
    private $date_of_birth;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Home", mappedBy="user")
     */
    private $homes;

    public function __construct()
    {
        $this->homes = new ArrayCollection();
    }

    /**
     * @var string[]
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="integer")
     */
    private $createdAt;

    public function __toString()
    {
        // TODO: Implement __toString() method.
        return (string)$this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * @param mixed $phone
     */
    public function setPhone($phone): void
    {
        $this->phone = $phone;
    }

    public function getDateOfBirth(): ?int
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(int $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    /**
     * @return Collection|Home[]
     */
    public function getHomes(): Collection
    {
        return $this->homes;
    }

    public function addHome(Home $home): self
    {
        if (!$this->homes->contains($home)) {
            $this->homes[] = $home;
            $home->setUser($this);
        }

        return $this;
    }

    public function removeHome(Home $home): self
    {
        if ($this->homes->contains($home)) {
            $this->homes->removeElement($home);
            // set the owning side to null (unless already changed)
            if ($home->getUser() === $this) {
                $home->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getUsername(): string
    {
        return (string)$this->phone;
    }

    /**
     * @return array
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param string[] $roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    /**
     * @return string
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    /**
     * @param string $password
     * @return User
     */
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getCreatedAt(): ?int
    {
        return $this->createdAt;
    }

    public function setCreatedAt(int $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @ORM\PrePersist()
     */
    public function setCreatedAtUser()
    {
        $this->setCreatedAt(time());
    }
}

src/Form/UserType.php
<?php


namespace App\Form;


use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null, [
                'label' => 'Имя'
            ])
            ->add('date_of_birth', BirthdayType::class, [
                'label' => 'Дата рождения',
                'input'  => 'timestamp'
            ])
            ->add('phone', null, [
                'label' => 'Телефон',
            ])
            ->add('password', PasswordType::class, [
                'label' => 'Пароль',
                'mapped' => false,
                'constraints' => [
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Пароль должен содержать хотя бы 6 символов!',
                        'max' => 4096,
                    ]),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php


namespace App\Controller;


use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_show', ['id' => $user->getId()]);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Вы уверены, что хотите удалить этого пользователя?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Удалить</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ include('menu/index.html.twig') }}

    {{ include('user/_form.html.twig', {'button_label': ' Сохранить'}) }}

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Пользователи</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Номер</th>
                <th>Имя</th>
                <th>Дата рождения</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.dateOfBirth|date() }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">показать</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">изменить</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">еще нет ни одного пользователя</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Добавить</a>

    <a href="{{ path('menu') }}">назад</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Добавить нового пользователя</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">назад</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ include('menu/index.html.twig') }}

    <section class="show">
        <h3>Ваш профиль</h3>
        <table class="table">
            <tbody>
                <tr>
                    <th>Имя</th>
                    <td>{{ user.name }}</td>
                </tr>
                <tr>
                    <th>Дата рождения</th>
                    <td>{{ user.dateOfBirth|date() }}</td>
                </tr>
            </tbody>
        </table>

        <a href="{{ path('user_edit', {'id': user.id}) }}"><button class="btn">Изменить</button></a>
        <a href="{{ path('app_logout') }}"><button class="btn">Выйти</button></a>
    </section>

{% endblock %}